export const flags = {
  bahrain: "https://flagcdn.com/bh.svg",
  jeddah: "https://flagcdn.com/sa.svg",
  albert_park: "https://flagcdn.com/au.svg",
  baku: "https://flagcdn.com/az.svg",
  miami: "https://flagcdn.com/us.svg",
  imola: "https://flagcdn.com/it.svg",
  monaco: "https://flagcdn.com/mc.svg",
  catalunya: "https://flagcdn.com/es.svg",
  villeneuve: "https://flagcdn.com/ca.svg",
  red_bull_ring: "https://flagcdn.com/at.svg",
  silverstone: "https://flagcdn.com/gb.svg",
  hungaroring: "https://flagcdn.com/hu.svg",
  spa: "https://flagcdn.com/be.svg",
  zandvoort: "https://flagcdn.com/nl.svg",
  monza: "https://flagcdn.com/it.svg",
  marina_bay: "https://flagcdn.com/sg.svg",
  suzuka: "https://flagcdn.com/jp.svg",
  losail: "https://flagcdn.com/qa.svg",
  americas: "https://flagcdn.com/us.svg",
  rodriguez: "https://flagcdn.com/mx.svg",
  interlagos: "https://flagcdn.com/br.svg",
  vegas: "https://flagcdn.com/us.svg",
  yas_marina: "https://flagcdn.com/ae.svg",
};
